name: CI

on: [push, pull_request]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./teste2e

    - name: Install Cypress binary
      run: npx cypress install
      working-directory: ./teste2e

    - name: Run Cypress tests
      run: npx cypress run 2> /dev/null
      working-directory: ./teste2e

  api_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./apiTest

    - name: Install Cypress binary
      run: npx cypress install
      working-directory: ./apiTest

    - name: Run Cypress tests
      run: npx cypress run 2> /dev/null
      working-directory: ./apiTest
